### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by westcoastfr** [xr1337/CookieBlockerIssueTracker#4]
In the site google.com shows the cookie consent banner. I would like the application to block all cookies from that domain or anyone. Thank you.

**Comment by xr1337** [comment]
Hi @westcoastfr 

Thank you for submitting this issue. 

Google.com cookies should be blocked/deleted. 
Your can test this out with Safari Inspector.

In a nutshell:
- Navigate to a web site.
- Select Show Web Inspector from the Develop menu (follow the headline link for instructions on turning on that menu if it doesn’t appear for you).
- Click the Storage tab in the web pane that appears.
- Click the Cookies item on the left side.

As for the `cookie consent banner.`,  unfortunately, this is UI ( user interface ) and the app doesn't hide it.
Regardless of the consents/not - the app will clear out the cookie storage on the browser.

If you need to hide the consent banner, there is a great app extension ( Free ) that blocks the banner from showing.
https://oblador.github.io/hush/

Thank you for the report
